### ISSUE TITLE
Missing user_project_wrapper inputs

### ISSUE THREAD

**Issue by vijayank88** [Nguyen-C-Dao/TinyRocket_SoC#1]
@Nguyen-C-Dao 
Missing https://github.com/Nguyen-C-Dao/TinyRocket_SoC/blob/701781a7e725a0bd1b24db70bcba0fcc7ca52f27/openlane/user_project_wrapper/config.tcl#L57
Also missing respective module DEF/LEF/GDS files required to run the flow.

**Comment by Nguyen-C-Dao** [comment]
@vijayank88 do you want to run openlane flow (make user_project_wrapper)? This repo is for mpw6 but missed the deadline.

**Comment by vijayank88** [comment]
Ok. Efabless website its shows precheck passed but nothing about Tapeout status.
Because of missing deadline.
Got it. Good luck for next shuttle.
